version: 2

models:
  - name: silver_commodities
    description: "Dados transformados das commodities."
    columns:
      - name: data
        description: "Data de observação no formato YYYY-MM-DD"
      - name: ticker
        description: "Símbolo da commodity"
      - name: valor_fechamento
        description: "Preço de fechamento da commodity com precisão decimal 10.2"

  - name: silver_movimentacao_commodities
    description: "Dados transformados de movimentações das commodities."
    columns:
      - name: data
        description: "Data da transação no formato YYYY-MM-DD"
      - name: ticker
        description: "Símbolo da commodity"
      - name: acao
        description: "Tipo de transação (buy/sell)"
      - name: quantidade
        description: "Quantidade transacionada"